@token = 1839c

GET http://localhost:3000/api/categorias
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/categorias/17


###

POST http://localhost:3000/api/categorias/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Categoria de prueba"
}


###

PUT http://localhost:3000/api/categorias/17
Content-Type: application/json

{
    "nombre": "Categoria de prueba editada"
}

###

DELETE http://localhost:3000/api/categorias/17