@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoicGF0aXRvQHV2Lm14IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXN1YXJpbyBwYXRpdG8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc3VhcmlvIiwiaXNzIjoiU2Vydmlkb3JGZWlKV1QiLCJhdWQiOiJDbGllbnRGZWlKV1QiLCJpYXQiOjE3MzM4MDM1ODgsImV4cCI6MTczMzgwNDc4OH0.zHqarJL_e5UyQsG4Sr0TAlIABvqIQrsQOACYDkJatGI


GET http://localhost:3000/api/compras
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/compras/2
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/compras/personal
Authorization: Bearer {{token}}


###

GET http://localhost:3000/api/compras/personal/7
Authorization: Bearer {{token}}

###

POST http://localhost:3000/api/compras
Content-Type: application/json
Authorization: Bearer {{token}}

{
}


###

POST http://localhost:3000/api/compras
Content-Type: application/json
Authorization: Bearer {{token}}

{
}

###

POST http://localhost:3000/api/compras
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productos": [
    ]
}

###

POST http://localhost:3000/api/compras
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productos": [
        {}
    ]
}

###

POST http://localhost:3000/api/compras
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productos": [
        {
            "productoid": 1
        }
    ]
}

###

POST http://localhost:3000/api/compras
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productos": [
        {
            "cantidad": 1
        }
    ]
}

###

POST http://localhost:3000/api/compras
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productos": [
        {
            "productoid": "1a"
        }
    ]
}

###

POST http://localhost:3000/api/compras
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productos": [
        {
            "cantidad": "1a"
        }
    ]
}