@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoicGF0aXRvQHV2Lm14IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXN1YXJpbyBwYXRpdG8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc3VhcmlvIiwiaXNzIjoiU2Vydmlkb3JGZWlKV1QiLCJhdWQiOiJDbGllbnRGZWlKV1QiLCJpYXQiOjE3MzMwOTgwMDAsImV4cCI6MTczMzA5OTIwMH0.M_c0lDCnUS5Q-tWziTlHUs8HD7MbdTXW_0haUUAvfJk


GET http://localhost:3000/api/productos
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/productos/200000
Authorization: Bearer {{token}}


###

POST http://localhost:3000/api/productos/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "Producto prueba",
    "descripcion": "Producto prueba ",
    "precio": 12.2,
    "archivoId": 1,
    "cantidadDisponible": 0
}


###

PUT http://localhost:3000/api/productos/20
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "Producto prueba editado",
    "descripcion": "Producto prueba descripcion editado",
    "precio": 12.2,
    "cantidadDisponible": 1
}

###

DELETE http://localhost:3000/api/productos/17
Authorization: Bearer {{token}}

###

POST http://localhost:3000/api/productos/20/categoria
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "categoriaid": 1
}

###

DELETE http://localhost:3000/api/productos/20/categoria/1