@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZ3ZlcmFAdXYubXgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJHdWlsbGVybW8gVmVyYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpc3MiOiJTZXJ2aWRvckZlaUpXVCIsImF1ZCI6IkNsaWVudEZlaUpXVCIsImlhdCI6MTczMTg2NzYyNiwiZXhwIjoxNzMxODY4ODI2fQ.Gp8LtXEgYlb5rrEL1DQRMciucColVHhCEbG0fLr406s

GET http://localhost:3000/api/usuarios
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/usuarios/sulem477@gmail.com
Authorization: Bearer {{token}}

###

POST http://localhost:3000/api/usuarios
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "sulem477@gmail",
    "password": "patito",
    "nombre": "melus",
    "protegido": 0,
    "rol": "Usuario"
}