@token = .eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoicGF0aXRvQHV2Lm14IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXN1YXJpbyBwYXRpdG8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc3VhcmlvIiwiaXNzIjoiU2Vydmlkb3JGZWlKV1QiLCJhdWQiOiJDbGllbnRGZWlKV1QiLCJpYXQiOjE3MzMwOTYyMzEsImV4cCI6MTczMzA5NzQzMX0.9HWtzqJCIsCmKhaQOi_VwJWyQeDEqLHb9yeoAqh0MZU

GET http://localhost:3000/api/usuarios
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/usuarios/sulem477@gmail.com
Authorization: Bearer {{token}}

###

POST http://localhost:3000/api/usuarios
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "sulem477@gmail",
    "password": "patito",
    "nombre": "melus",
    "protegido": 0,
    "rol": "Usuario"
}


### No Sale
PUT http://localhost:3000/api/usuarios/
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "nombre": "melus",
    "protegido": 0,
    "rol": "Usuario"
}

###ERROR 500
DELETE http://localhost:3000/api/usuarios/sulem477@gmail.com
Authorization: Bearer {{token}}